apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true