apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timothyw-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/timothywashburn/timothyw-system
    path: helm
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: timothyw-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/source/helm/parameters
