global:
  dashboardDomain: k8s.timothyw.dev
  argoCDDomain: argo.timothyw.dev
  grafanaDomain: grafana.timothyw.dev
  loadBalancerIP: "64.71.152.179"

infrastructure:
  traefik:
    rbacFix:
      enabled: true
  metallb:
    enabled: true
  dashboard:
    enabled: true
  argocd:
    enabled: true
  monitoring:
    enabled: true

argocdApplications:
  applications:
    - name: pat
      namespace: pat
      repoURL: https://github.com/timothywashburn/pat-api
      branch: main
      path: helm
      images:
        - alias: server
          image: kyrokrypt/pat-api
          pullSecret: pat/dockerhub-registry
        - alias: client
          image: kyrokrypt/pat-app
          pullSecret: pat/dockerhub-registry