global:
  dashboardDomain: k8s.timothyw.dev
  argoCDDomain: argo.timothyw.dev
  grafanaDomain: grafana.timothyw.dev
  loadBalancerIP: "64.71.152.179"

infrastructure:
  traefik:
    rbacFix:
      enabled: true
  metallb:
    enabled: true
  dashboard:
    enabled: true
  argocd:
    enabled: true
  monitoring:
    enabled: true

applications:
  - name: pat
    namespace: pat
    repoURL: https://github.com/timothywashburn/pat-api
    branch: main
    path: helm
    images:
      - alias: client
        image: kyrokrypt/pat-app
        pullSecret: pat/dockerhub-registry
      - alias: server
        image: kyrokrypt/pat-api
        pullSecret: pat/dockerhub-registry
  - name: clubhive-test
    namespace: clubhive-test
    repoURL: https://github.com/timothywashburn/clubhive
    branch: main
    path: helm
    valuesFile: values-prod.yaml
    images:
      - alias: client
        image: kyrokrypt/clubhive-client-main
        pullSecret: clubhive/dockerhub-registry
      - alias: server
        image: kyrokrypt/clubhive-server-main
        pullSecret: clubhive/dockerhub-registry